VRK-YTI/yti-terminology-api

src/main/java/fi/vm/yti/terminology/api/importapi/NtrfMapper.java

While unmarshalling from xml to java classes the characters will get unescaped (e.g. `&amp;` -> &). These are re-escaped in the ntrf mapper, because in the frontend content is interpreted as xml.

YTI-1151 Escape xml characters

---

src/main/java/fi/vm/yti/terminology/api/importapi/NtrfMapper.java

Remove trim() from note string when adding link to the text.

YTI-1351: Fix adding links to notes

---

src/main/java/fi/vm/yti/terminology/api/importapi/NtrfMapper.java

Escape only string content, not the whole note string

YTI-1151 fix escaping note string

---

build.gradle

Replace jaxb core with jaxb runtime dependency. Xml import didn't work with the first one

YTI-448 add jaxb runtime dependency

---

src/main/java/fi/vm/yti/terminology/api/frontend/FrontendController.java
src/main/java/fi/vm/yti/terminology/api/frontend/FrontendElasticSearchService.java
src/main/java/fi/vm/yti/terminology/api/frontend/elasticqueries/CountQueryFactory.java
src/main/java/fi/vm/yti/terminology/api/frontend/searchdto/CountDTO.java
src/main/java/fi/vm/yti/terminology/api/frontend/searchdto/CountSearchResponse.java

Add /counts endpoint, which lists the number of documents in vocabularies and concepts grouped by index, status and group.
The implementation is done as a single elasticsearch query utilizing aggregations.
YTI-1583
Example response:
```json
{
"totalHitCount": 18892,
"counts": {
"indices": {
"vocabularies": 69,
"concepts": 18823
},
"statuses": {
"DRAFT": 18158,
"SUPERSEDED": 7,
"VALID": 573,
"RETIRED": 51,
"INCOMPLETE": 11,
"SUGGESTED": 88,
"INVALID": 4
},
"groups": {
"b4dc527b-5465-3b82-871a-2a982e23554b": 4,
"11b4cac3-e350-4de1-8886-baadd5ed2e83": 12,
"1143c41d-10ec-4b13-a97a-7d28328070af": 5
}
}
}
```

add /counts endpoint

---

src/main/java/fi/vm/yti/terminology/api/frontend/FrontendElasticSearchService.java
src/main/java/fi/vm/yti/terminology/api/frontend/elasticqueries/DeepConceptQueryFactory.java
src/main/java/fi/vm/yti/terminology/api/frontend/elasticqueries/TerminologyQueryFactory.java
src/main/java/fi/vm/yti/terminology/api/frontend/searchdto/TerminologySearchRequest.java
src/main/java/fi/vm/yti/terminology/api/util/ElasticRequestUtils.java
src/main/resources/create_vocabulary_mappings.json

This PR adds more search filters to the terminology/vocabulary search.
* status (Text array)
* groups (UUID array)
* terminology types (Text array)
A terminology search actually performs three consecutive searches, if a deep concept search is requested.
1. terminologies matching organization to show "INCOMPLETE" items for those with access
2. concepts with the same text search, their terminologies added to the end result
3. terminologies (vocabularies)
If deep search was not requested, the first two queries are not executed.
One of the new search options is "status", and this is added to both concept and vocabulary query. Group and type filters are only added to the terminology query.
A couple new mappings have been added to `create_vocabulary_mappings.json`.
* `type.id`
* …

YTI-1582 extend terminology search with new options

---

src/main/java/fi/vm/yti/terminology/api/frontend/elasticqueries/TerminologyQueryFactory.java
src/main/java/fi/vm/yti/terminology/api/frontend/searchdto/TerminologySearchRequest.java

This PR adds one more search filter to the terminology/vocabulary search. The implementation is exactly the same as when groupIds were added in #25
Example search with curl:
```sh
curl 'http://localhost:3000/terminology-api/api/v1/frontend/searchTerminology' \
-H 'Cache-Control: no-cache' \
-H 'Accept: */*' \
-d @- << EOF
{
"organizations": [
"d9c76d52-03d3-4480-8c2c-b66e6d9c57f2"
],
"searchConcepts": false,
"prefLang": "fi",
"pageSize": 10,
"pageFrom": 0
}
EOF
```

YTI-1582 add organization filter to terminology search

---

src/main/java/fi/vm/yti/terminology/api/frontend/elasticqueries/TerminologyQueryFactory.java

Query string will now apply to organization label as well, in addition to the terminology label.
Search by organization IDs was added in #27, but it was then determined that the preferred approach would be to search the organization name instead. The previous implementation is left as-is, although it might no be used.
Example search with curl:
```sh
curl 'http://localhost:3000/terminology-api/api/v1/frontend/searchTerminology' \
-H 'Cache-Control: no-cache' \
-H 'Accept: */*' \
-d @- << EOF
{
"query": "Testiorganisaatio",
"searchConcepts": false,
"prefLang": "fi",
"pageSize": 10,
"pageFrom": 0
}
EOF
```
Which will add the following kind of filter to the ES query:
```json
"query_string": {
"query": "Testiorganisaatio Testiorganisaatio* …
```

extend terminology search query to organization label

---

src/main/java/fi/vm/yti/terminology/api/synchronization/GroupManagementOrganization.java

This change is made to make deployment easier during transitional phase when groupmanagement is introducing a new property.
YTI-1593

ignore unknown fields as a workaround

---

src/main/java/fi/vm/yti/terminology/api/frontend/FrontendController.java
src/main/java/fi/vm/yti/terminology/api/frontend/FrontendGroupManagementService.java
src/test/java/fi/vm/yti/terminology/service/FrontendGroupmanagementServiceTest.java

Possibility to define for which services the access is requested instead of hard coded Terminology access. 
Sample request
```
curl -X POST "http://localhost:9103/terminology-api/api/v1/frontend/request?organizationId=<id>&roles=TERMINOLOGY_EDITOR&roles=CODE_LIST_EDITOR" \
-H "Cookie: JSESSIONID=xxx" -H "Content-Type: application/json"
```

YTI-1711 Add multiple roles for user

---

src/main/java/fi/vm/yti/terminology/api/frontend/FrontendController.java
src/main/java/fi/vm/yti/terminology/api/frontend/FrontendTermedService.java
src/main/java/fi/vm/yti/terminology/api/security/AuthorizationManager.java
src/test/java/fi/vm/yti/terminology/api/frontend/FrontendTermedServiceTest.java

This feature allows mass updating several nodes with a new status, matching the provided node type and existing status.
Example request with curl:
```sh
curl \
-X POST \
-H 'Accept: */*' \
-H 'Cookie: 36ECA8FBF0C8EBB83A8049F27BC1E0F3' \
"http://localhost:9103/terminology-api/api/v1/frontend/modifyStatuses?graphId=933a668f-41ea-4312-8081-26312194fced&oldStatus=DRAFT&newStatus=VALID&types=Term,Concept"
```
YTI-1741

Add endpoint for mass updating statuses of nodes

---

src/main/java/fi/vm/yti/terminology/api/exception/NamespaceInUseException.java
src/main/java/fi/vm/yti/terminology/api/exception/VocabularyNotFoundException.java
src/main/java/fi/vm/yti/terminology/api/frontend/FrontendController.java
src/main/java/fi/vm/yti/terminology/api/frontend/FrontendTermedService.java
src/main/java/fi/vm/yti/terminology/api/frontend/searchdto/CreateVersionDTO.java
src/main/java/fi/vm/yti/terminology/api/frontend/searchdto/CreateVersionResponse.java
src/main/java/fi/vm/yti/terminology/api/migration/AttributeIndex.java
src/main/java/fi/vm/yti/terminology/api/migration/task/V20_AddOriginProperty.java
src/main/java/fi/vm/yti/terminology/api/model/termed/Dump.java
src/main/java/fi/vm/yti/terminology/api/model/termed/GenericNode.java
src/main/java/fi/vm/yti/terminology/api/security/AuthorizationManager.java
src/test/java/fi/vm/yti/terminology/api/frontend/FrontendTermedServiceTest.java

* Create a copy of the terminology and store it as new version
* Create new text attribute `origin` to hold information from which terminology new version is created 
```
curl -X POST "http://localhost:9103/terminology-api/api/v1/frontend/createVersion"  \ 
-H "Content-Type: application/json" \
-H "Cookie: JSESSIONID=xxx" \
-d '{"graphId": "1e10f214-2791-48d9-b996-4ea0d3f74b8d",  "newCode": "test_v2"}'
```

YTI-1742 Create new version of the terminology

---

src/main/java/fi/vm/yti/terminology/api/ExceptionHandlerAdvice.java
src/main/java/fi/vm/yti/terminology/api/frontend/FrontendController.java
src/main/java/fi/vm/yti/terminology/api/model/rest/ApiError.java
src/main/java/fi/vm/yti/terminology/api/model/rest/ApiValidationError.java
src/main/java/fi/vm/yti/terminology/api/model/rest/ApiValidationErrorDetails.java
src/main/java/fi/vm/yti/terminology/api/model/termed/GenericNode.java
src/main/java/fi/vm/yti/terminology/api/validation/ValidVocabularyNode.java
src/main/java/fi/vm/yti/terminology/api/validation/VocabularyNodeValidator.java
src/test/java/fi/vm/yti/terminology/api/frontend/FrontendControllerTest.java

Validation of vocabulary nodes is now implemented with a custom validation constraint, which is enabled specifically for the `vocabularyNode` argument of the `createVocabulary` method in `FrontendController`.
This is done with a single validator (`VocabularyNodeValidator`) instead of applying smaller validators directly in `GenericNode`, with the assumption that these validations might be specific to this use case and `GenericNode` may still have other uses where different validations may be needed.
The `createVocabulary` controller method has also been extended with a new parameter `validateOnly`, which will skip the actual vocabulary creation, and can be used to only validate input.
Validation errors are returned to user as JSON objects representing the newly added `ApiValidationError`, …

Add validation of vocabulary nodes in frontend controller

---

src/main/java/fi/vm/yti/terminology/api/migration/AttributeIndex.java
src/main/java/fi/vm/yti/terminology/api/migration/task/V22_LinkAndSubjectAreaProperties.java
src/main/java/fi/vm/yti/terminology/api/validation/VocabularyNodeValidator.java

* Validate terminologyType only if given
* Remove regular  expression from terminologyType
* Remove redundant property termEquivalencyRelation from term
It's quite a bad practice to modify existing migration scripts but since changes are deployed only dev environment, I think it's clearer in this case manually clean up the database, rather than create new migration script to revert these changes. Besides, changing regular expression is not even possible to modify with existing functionalities

YTI-1886 Validation and migration changes

---

src/main/java/fi/vm/yti/terminology/api/frontend/elasticqueries/ConceptQueryFactory.java
src/main/java/fi/vm/yti/terminology/api/frontend/elasticqueries/TerminologyQueryFactory.java
src/main/java/fi/vm/yti/terminology/api/index/Concept.java
src/main/java/fi/vm/yti/terminology/api/index/IndexElasticSearchService.java
src/main/java/fi/vm/yti/terminology/api/index/Vocabulary.java
src/main/java/fi/vm/yti/terminology/api/util/IndexUtil.java

* By default show only statuses DRAFT, VALID, INCOMPLETE and SUGGESTED
* Add sortBy labels for terminologies and concepts for each language

YTI-1871 Default statuses and sorting

---

src/main/java/fi/vm/yti/terminology/api/importapi/excel/ExcelCreator.java

In some cases there is language defined for term properties which are not localized (e.g. termConjugation). Consequently, language suffix is added to the header. This causes an error because excel import assumes that term properties are not localized, except prefLabel.

YTI-1448 ignore possible language from term data

---

src/main/java/fi/vm/yti/terminology/api/importapi/ExcelImportJmsListener.java
src/main/java/fi/vm/yti/terminology/api/importapi/ImportService.java
src/main/java/fi/vm/yti/terminology/api/importapi/YtiMQService.java
src/main/java/fi/vm/yti/terminology/api/util/JsonUtils.java

- Handle error status if saving to Termed has been failed
- Add jobtoken to log messages
```
{
"status" : "FAILURE",
"resultsError" : 1,
"statusMessage" : [ {
"level" : "ERROR",
"targetIdentifier" : "Vocabulary",
"message" : "Termed error, reference: 4a66e598-f7fe-42be-8aae-de6985536e57"
} ]
}
```

YTI-1927 Improve error handling and logging

---

src/main/java/fi/vm/yti/terminology/api/frontend/FrontendTermedService.java
src/main/java/fi/vm/yti/terminology/api/security/DefaultAuthorizationTermedService.java
src/test/java/fi/vm/yti/terminology/api/frontend/FrontendTermedServiceTest.java
src/test/java/fi/vm/yti/terminology/service/DefaultAuthorizationTermedServiceTest.java

- Use session scope instead of request scope in DefaultAuthorizationTermedService, because caching doesn't work, if new instance is created for each request
- Use guava cache with configurable expiration time and added caching also for fetching organizations and groups

YTI-1884 Fix termed service caching

---

src/main/java/fi/vm/yti/terminology/api/importapi/ExcelImportJmsListener.java
src/main/java/fi/vm/yti/terminology/api/importapi/ImportUtil.java
src/main/java/fi/vm/yti/terminology/api/importapi/YtiMQService.java
src/main/java/fi/vm/yti/terminology/api/model/termed/GenericDeleteAndSave.java
src/test/java/fi/vm/yti/terminology/api/importapi/ExcelImportListenerTest.java

Use patch, when importing nodes from excel. Thus, existing properties won't override in case it is missing from excel. 
Also, added some performace improvements to handling excel data.
Termed [PR](https://github.com/VRK-YTI/termed-api/pull/2)

YTI-1923 patch existing nodes in excel import

---

src/main/java/fi/vm/yti/terminology/api/frontend/elasticqueries/TerminologyQueryFactory.java
src/main/resources/create_vocabulary_mappings.json

Map language as a keyword because without mapping it wouldn't match locales with hyphen

YTI-1908 Fix searching by language

---

src/main/java/fi/vm/yti/terminology/api/frontend/elasticqueries/ConceptQueryFactory.java
src/main/java/fi/vm/yti/terminology/api/frontend/elasticqueries/DeepConceptQueryFactory.java
src/main/java/fi/vm/yti/terminology/api/index/Concept.java
src/main/resources/create_concept_mappings.json
src/test/java/fi/vm/yti/terminology/elasticsearch/query/ConceptQueryFactoryTest.java
src/test/resources/es/request/concept_request.json
src/test/resources/es/request/deep_concept_request.json

Changelog:
- Added the following terms to elastic search query in terminology search and concept search. 
- altLabel (5 boost)
- searchTerm (3 boost)
- hiddenTerm (3 boost)
- notRecommendedSynonym (1.5 boost)
- Added elasticsearch indexing for the same terms
- Unit test for the creation of the queries for these terms
- Fixed some minor recommended code smells

Yti 1793 search modifications

---

src/main/java/fi/vm/yti/terminology/api/frontend/elasticqueries/ConceptQueryFactory.java
src/main/java/fi/vm/yti/terminology/api/frontend/elasticqueries/TerminologyQueryFactory.java

Unmapped types set an empty value of specified type (instead of null) if the field is unmapped. In this case all the languages in sortByLabel.
This bug fix wont be noticed on a database with data already in it. 
Fixed some small sonarqube issues

Added unmapped types to concept and vocabulary searches.

---

src/main/java/fi/vm/yti/terminology/api/util/ElasticRequestUtils.java
src/test/java/fi/vm/yti/terminology/elasticsearch/query/ElasticRequestUtilsTest.java

Changelog:
- Add custom escaping function, copied from Lucene. 
- Added all characters needed for escaping elasticsearch query
- Changed escape to handle being added as a json body
- This means more '\' characters
- Unit tests for checking escape characters.

buildPrefixSufficQuery now sanitizes input by escaping all characters.

---

src/main/java/fi/vm/yti/terminology/api/frontend/FrontendController.java
src/main/java/fi/vm/yti/terminology/api/frontend/FrontendTermedService.java
src/test/java/fi/vm/yti/terminology/api/frontend/FrontEndControllerInternalNodeTests.java

If node exists, it will be added to the patch list, so it will be merged with the old one in Termed (missing properties are not deleted from the old node).

YTI-2057 Patch existing nodes instead of overwriting

---

src/main/java/fi/vm/yti/terminology/api/frontend/elasticqueries/DeepConceptQueryFactory.java
src/test/resources/es/request/deep_concept_request.json

Changelog:
- Elasticsearch DeepConceptQuery takes into account that the vocabulary where we are doing the deep search should not be INCOMPLETE

YTI-2064: Search result contains incomplete terminologies

---

src/main/java/fi/vm/yti/terminology/api/frontend/FrontendController.java
src/main/java/fi/vm/yti/terminology/api/frontend/FrontendElasticSearchService.java
src/main/java/fi/vm/yti/terminology/api/frontend/elasticqueries/TerminologyQueryFactory.java
src/main/java/fi/vm/yti/terminology/api/index/IndexTermedService.java
src/test/java/fi/vm/yti/terminology/elasticsearch/query/TerminologyQueryFactoryTest.java
src/test/resources/es/request/terminology_by_id_request.json

- Pass required graph ids to termed, so the query executed right after cache invalidation is not so heavy. 
- Created endpoint /simpleVocabulary, which returns limited amount of information fetched from Elasticsearch. This can be used if only e.g. name and id of the terminology are needed
See [termed changes](https://github.com/VRK-YTI/termed-api/pull/3)

YTI-1936 optimize fetching terminology

---

src/main/java/fi/vm/yti/terminology/api/exception/ExcelParseException.java
src/main/java/fi/vm/yti/terminology/api/importapi/excel/ExcelParser.java

Instead of empty message, return following response
```
{"message":"Row 0 doesn't exist, sheet Concepts","errorDetails":{}}
```

YTI-2085 Add error message to response if row does not exist

---

src/main/java/fi/vm/yti/terminology/api/frontend/FrontendController.java
src/main/java/fi/vm/yti/terminology/api/frontend/FrontendTermedService.java
src/main/java/fi/vm/yti/terminology/api/security/DefaultAuthorizationTermedService.java
src/test/java/fi/vm/yti/terminology/api/frontend/FrontendTermedServiceTest.java
src/test/java/fi/vm/yti/terminology/service/DefaultAuthorizationTermedServiceTest.java

- Use `/graph` endpoints instead of `/node-trees` for fetching organization ids and collections' count. These queries perform much better in termed
- Add graphTypeId parameters for /node-trees requests to make them lighter (see termed-api [PR](https://github.com/VRK-YTI/termed-api/pull/3))

YTI-2115 performance improvements

---

src/main/java/fi/vm/yti/terminology/api/frontend/elasticqueries/ConceptQueryFactory.java
src/main/java/fi/vm/yti/terminology/api/frontend/elasticqueries/DeepConceptQueryFactory.java
src/main/java/fi/vm/yti/terminology/api/frontend/elasticqueries/TerminologyQueryFactory.java
src/main/java/fi/vm/yti/terminology/api/index/IndexTermedService.java
src/main/resources/create_concept_mappings.json
src/main/resources/create_index_default.json
src/test/resources/es/request/concept_request.json
src/test/resources/es/request/deep_concept_request.json
src/test/resources/es/request/vocabulary_request.json

- Search also from concetp's definition
- Sort results alphabetically only if sortBy is specified or query is not specified
- Simplify indexing by using standard analyzer instead of custom one with ngram tokenizer
- Fix indexing for notRecommendedSynonym and searchTerm
- Change boosts in terminology search: matching terminology's name is more important than organization name

YTI-2127 concept search improvements

---

src/main/java/fi/vm/yti/terminology/api/migration/MigrationService.java
src/main/java/fi/vm/yti/terminology/api/migration/task/V23_ChangeHiddenTerms.java

Add new migration script:
- get all nodes with type Concept and reference attribute hiddenTerm
- add hiddenTerms to searchTerm list (create new list if no searchTerms found)
- remove hiddenTerm attribute
- save updated nodes

YTI-2128 migration script for changing hiddenTerms to searchTerms

---

src/main/java/fi/vm/yti/terminology/api/frontend/FrontendTermedService.java
src/test/java/fi/vm/yti/terminology/api/frontend/FrontendTermedServiceTest.java

Remove trailing slash from uri because it causes problems in fetching concepts from datamodel application

YTI-2197 remove trailing slash from uri

---

src/main/java/fi/vm/yti/terminology/api/frontend/FrontendController.java
src/main/java/fi/vm/yti/terminology/api/frontend/FrontendTermedService.java
src/main/java/fi/vm/yti/terminology/api/frontend/searchdto/StatusCountDTO.java
src/main/java/fi/vm/yti/terminology/api/frontend/searchdto/StatusCountSearchResponse.java

Changes in this PR:
- Added new endpoint `/statusCounts` which returns total amounts of different statuses of a terminologies concepts and terms

Endpoint for status counts added

---

src/main/java/fi/vm/yti/terminology/api/TermedRequester.java
src/main/java/fi/vm/yti/terminology/api/frontend/FrontendController.java
src/main/java/fi/vm/yti/terminology/api/frontend/FrontendTermedService.java
src/main/java/fi/vm/yti/terminology/api/migration/task/V25_RemoveTermedSuffix.java
src/main/java/fi/vm/yti/terminology/api/model/termed/GenericNode.java
src/main/java/fi/vm/yti/terminology/api/resolve/ResolveService.java
src/test/java/fi/vm/yti/terminology/api/resolve/ResolveServiceTest.java

Changelog:
- send custom uri to termed api so it does not append suffix during vocabulary. 
- resolve works with or without trailing forward-slash now. 
- fixed a bunch of sonarqube issues
- unit tests

YTI-2584: remove terminology suffix

---

src/main/java/fi/vm/yti/terminology/api/migration/task/V26_UpdateMissingStatuses.java

Add status property for concepts and terms in case it's missing.
This [PR](https://github.com/VRK-YTI/yti-terminology-api/pull/122) must be merged first, otherwise migration scripts are not sequential

YTI-2642 migration for adding missing statuses

---

src/main/java/fi/vm/yti/terminology/api/integration/IntegrationService.java

Datamodel application requires, that terminology uri ends with `/`.  However, since the URIs don't contain terminological-vocabulary-0 suffix, the prefix query from Elasticsearch didn't work any more. -> Add trailing slash to response but remove it for the search.

Integration api search fix

---

src/main/java/fi/vm/yti/terminology/api/importapi/NtrfMapper.java
src/test/java/fi/vm/yti/terminology/api/importapi/NtrfTest.java

Notes are displayed newest first. That's why we need to reverse note list to make sure that first note in the xml file is on top of the list in the UI.

YTI-3683 reverse note list in NTRF import

---

src/main/java/fi/vm/yti/terminology/api/importapi/NtrfMapper.java
src/test/resources/concept-definition-and-note.xml

The B and I tags were ignored in notes, causing parts of the text to be missing.
This change adds supports for those two tags, but any other unknown tags will still be ignored.

support B and I elements in NTRF import

---

src/main/java/fi/vm/yti/terminology/api/v2/dto/ConceptCollectionDTO.java
src/main/java/fi/vm/yti/terminology/api/v2/dto/ConceptCollectionInfoDTO.java
src/main/java/fi/vm/yti/terminology/api/v2/endpoint/ConceptCollectionController.java
src/main/java/fi/vm/yti/terminology/api/v2/mapper/ConceptCollectionMapper.java
src/main/java/fi/vm/yti/terminology/api/v2/service/ConceptCollectionService.java
src/main/java/fi/vm/yti/terminology/api/v2/util/TerminologyURI.java
src/main/java/fi/vm/yti/terminology/api/v2/validator/ConceptCollectionValidator.java
src/main/java/fi/vm/yti/terminology/api/v2/validator/ValidConceptCollection.java
src/test/java/fi/vm/yti/terminology/api/v2/TestUtils.java
src/test/java/fi/vm/yti/terminology/api/v2/endpoint/ConceptCollectionControllerTest.java
src/test/java/fi/vm/yti/terminology/api/v2/service/ConceptCollectionServiceTest.java
src/test/resources/terminology-with-concept-collections.ttl

* basic end points for get/add/update/delete/exists
* each collection may contain a number of "members", which point to concepts
* When adding or updating, members should be just strings, e.g.: `[ "concept-1", "concept-2" ]`
* When retreiving a collection, concepts will contain some extra details from concept, but not a full concept
* **Indexing is not yet implemented!**
```sh
"$BASE_URL/terminology-api/v2/collection/urhotest1" \
-X POST \
-H "Authorization: Bearer $APIKEY" \
--data-binary @- << EOF
{
"identifier": "collection-1",
"label": {
"fi": "Testikokoelma 1",
"en": "Test collection 1"
},
"description": 7
"fi": "Testikokoelman kuvaus 1",
"en": "Test collection description 1"
},
"members": [ "concept-1", "concept-2" ]
}
EOF
```
```sh
curl -sS …
```

Add support for concept collections

---

src/main/java/fi/vm/yti/terminology/api/v2/config/SpringAsyncConfig.java
src/main/java/fi/vm/yti/terminology/api/v2/dto/TermDTO.java
src/main/java/fi/vm/yti/terminology/api/v2/mapper/ConceptCollectionMapper.java
src/main/java/fi/vm/yti/terminology/api/v2/mapper/ConceptMapper.java
src/main/java/fi/vm/yti/terminology/api/v2/migration/v1/Termed.java
src/main/java/fi/vm/yti/terminology/api/v2/migration/v1/TermedDataMapper.java
src/main/java/fi/vm/yti/terminology/api/v2/migration/v1/TermedMigrationController.java
src/main/java/fi/vm/yti/terminology/api/v2/migration/v1/TermedMigrationService.java
src/main/java/fi/vm/yti/terminology/api/v2/service/ConceptService.java
src/main/java/fi/vm/yti/terminology/api/v2/service/IndexService.java
src/test/java/fi/vm/yti/terminology/api/v2/mapper/ConceptMapperTest.java
src/test/java/fi/vm/yti/terminology/api/v2/migration/TermedDataMapperTest.java
src/test/java/fi/vm/yti/terminology/api/v2/service/ConceptServiceTest.java
src/test/resources/terminology-with-concepts.ttl
src/test/resources/v1-migration/termed-data.ttl

Migrate terminologies and concepts from Termed to Fuseki
Other changes:
- Add missing properties for term (sources and editorialNotes)
- Map concept's external references (e.g. narrowMatch)
- Create collection members as resources, not literals
- Handle multiple terms by type
- Use bulk operations when indexing concepts

YTI-4055 migration

---

src/main/java/fi/vm/yti/terminology/api/v2/StartUpListener.java
src/main/java/fi/vm/yti/terminology/api/v2/dto/ConceptSearchResultDTO.java
src/main/java/fi/vm/yti/terminology/api/v2/dto/TerminologySearchResultDTO.java
src/main/java/fi/vm/yti/terminology/api/v2/endpoint/FrontendController.java
src/main/java/fi/vm/yti/terminology/api/v2/mapper/ConceptMapper.java
src/main/java/fi/vm/yti/terminology/api/v2/opensearch/ConceptQueryFactory.java
src/main/java/fi/vm/yti/terminology/api/v2/opensearch/ConceptSearchRequest.java
src/main/java/fi/vm/yti/terminology/api/v2/opensearch/IndexConcept.java
src/main/java/fi/vm/yti/terminology/api/v2/opensearch/TerminologyQueryFactory.java
src/main/java/fi/vm/yti/terminology/api/v2/opensearch/TerminologySearchRequest.java
src/main/java/fi/vm/yti/terminology/api/v2/service/IndexService.java
src/main/java/fi/vm/yti/terminology/api/v2/service/SearchIndexService.java
src/test/java/fi/vm/yti/terminology/api/v2/TestUtils.java
src/test/java/fi/vm/yti/terminology/api/v2/endpoint/FrontendControllerTest.java
src/test/java/fi/vm/yti/terminology/api/v2/endpoint/TerminologyControllerTest.java
src/test/java/fi/vm/yti/terminology/api/v2/opensearch/ConceptQueryFactoryTest.java
src/test/java/fi/vm/yti/terminology/api/v2/opensearch/TerminologyQueryFactoryTest.java
src/test/resources/opensearch/concept-exceptions-request.json
src/test/resources/opensearch/concept-request.json
src/test/resources/opensearch/concept-superuser-request.json
src/test/resources/opensearch/terminology-deep-request.json
src/test/resources/opensearch/terminology-deep-superuser-request.json
src/test/resources/opensearch/terminology-request.json

New endpoints in FrontendController:
- search-concepts
- search-terminologies
The terminology search supports "deep search" by doing another search within concepts using the same search parameters.
Querying counts is currently not implemented.
Example terminology query:
```sh
curl -sS "$BASE_URL/terminology-api/v2/frontend/search-terminologies?query=test&searchConcepts=true&sortLang=en" \
-H "Authorization: Bearer $APIKEY" \
| jq
```
Example concept query:
```sh
curl -sS "$BASE_URL/terminology-api/v2/frontend/search-concepts?namespace=https://iri.suomi.fi/terminology/test/&status=VALID,INCOMPLETE&sortLang=en&pageSize=1000" \
-H "Authorization: Bearer $APIKEY" \
| jq
```

YTI-3951 terminology & concept search

---

src/main/java/fi/vm/yti/terminology/api/v2/integration/IntegrationController.java
src/main/java/fi/vm/yti/terminology/api/v2/integration/IntegrationResponse.java
src/main/java/fi/vm/yti/terminology/api/v2/integration/IntegrationResult.java
src/main/java/fi/vm/yti/terminology/api/v2/integration/IntegrationService.java
src/main/java/fi/vm/yti/terminology/api/v2/integration/Meta.java
src/test/java/fi/vm/yti/terminology/api/v2/service/IntegrationServiceTest.java
src/test/resources/integration/container-search-request.json
src/test/resources/integration/resource-search-request.json

Create simplified integration API (see [old implementation](https://github.com/VRK-YTI/yti-terminology-api/tree/develop/src/main/java/fi/vm/yti/terminology/api/integration)) for sending notifications (messaging-api) and adding concept references (codelist-content-intake-service). Support both GET and POST methods and both old (/api/v1/integrations) and new (v2/integrations) application path.
```
curl -X POST \
-H 'content-type: application/json' \
--data '{"uri": ["https://iri.suomi.fi/terminology/demo/"]}' \
http://localhost:9103/terminology-api/v2/integration/containers
```
```
curl -X POST \
-H 'content-type: application/json' \
--data '{
"container": ["https://iri.suomi.fi/terminology/demo/"],
"after": "2024-07-24T00:00:00",
"before": "2024-07-25T00:00:00",
"searchTerm": "Test", …
```

YTI-4054 send notifications

---

src/main/java/fi/vm/yti/terminology/api/v2/enums/TermFamily.java
src/main/java/fi/vm/yti/terminology/api/v2/mapper/NTRFMapper.java
src/main/java/fi/vm/yti/terminology/api/v2/migration/v1/TermedDataMapper.java
src/main/java/fi/vm/yti/terminology/api/v2/migration/v1/TermedMigrationService.java
src/main/java/fi/vm/yti/terminology/api/v2/repository/TerminologyRepository.java
src/main/java/fi/vm/yti/terminology/api/v2/service/TerminologyService.java
src/test/java/fi/vm/yti/terminology/api/v2/TestUtils.java
src/test/java/fi/vm/yti/terminology/api/v2/mapper/ConceptMapperTest.java
src/test/java/fi/vm/yti/terminology/api/v2/service/TerminologyServiceTest.java
src/test/resources/terminology-with-concepts.ttl

- Migration performance improvement: Map all resources to Jena model and save them at once instead of saving single resources. 
- Use simple CONSTRUCT query for fetching terminology metadata. If the whole model is fetched, i'll cause significant lag when fetching larger terminologies.
- Add model cache, because current implementation requires, that the whole model has to be fetched when fetching single resource (concept or collection)
Other fix: Renamed enum constant NEUTRAL -> NEUTER per feedback

YTI-4244 Improve performance

---

src/main/java/fi/vm/yti/terminology/api/v2/migration/v1/TermedDataMapper.java
src/main/java/fi/vm/yti/terminology/api/v2/migration/v1/TermedMigrationService.java
src/main/java/fi/vm/yti/terminology/api/v2/opensearch/TerminologyQueryFactory.java
src/test/java/fi/vm/yti/terminology/api/v2/opensearch/TerminologyQueryFactoryTest.java
src/test/resources/opensearch/terminology-deep-request.json
src/test/resources/opensearch/terminology-deep-superuser-request.json
src/test/resources/opensearch/terminology-request.json

Fix data during migration process 
- homograph number, e.g. `II` -> 2
- missing languages
- add better logging, if the whole terminology migration fails
Change search logic to include particular statuses by default. This functionality is copied from the old application.

Migration data fix and change to terminology search logic

---

src/main/java/fi/vm/yti/terminology/api/v2/mapper/ConceptMapper.java
src/main/java/fi/vm/yti/terminology/api/v2/opensearch/ConceptQueryFactory.java
src/main/java/fi/vm/yti/terminology/api/v2/opensearch/IndexConcept.java
src/main/java/fi/vm/yti/terminology/api/v2/opensearch/TerminologyQueryFactory.java
src/main/java/fi/vm/yti/terminology/api/v2/service/IndexService.java
src/test/java/fi/vm/yti/terminology/api/v2/mapper/ConceptMapperTest.java
src/test/java/fi/vm/yti/terminology/api/v2/opensearch/ConceptQueryFactoryTest.java
src/test/java/fi/vm/yti/terminology/api/v2/opensearch/TerminologyQueryFactoryTest.java
src/test/resources/opensearch/concept-exceptions-request.json
src/test/resources/opensearch/concept-query-with-sort.json
src/test/resources/opensearch/concept-request.json
src/test/resources/opensearch/concept-superuser-request.json
src/test/resources/opensearch/terminology-deep-request.json
src/test/resources/opensearch/terminology-deep-superuser-request.json
src/test/resources/opensearch/terminology-request.json

Search performs quite bad with ~30k documents. Simplify mappings by mapping definition and other terms than preferred term without sort key (results are sorted only by preferred term). So instead of mapping e.g. searchTerm with dynamic template like this:
```
"dynamic_templates": [
{
"label": {
"path_match": "searchTerm.*",
"mapping": {
"fields": {
"sortKey": {
"normalizer": "lowercase",
"ignore_above": 256,
"type": "keyword"
}
},
"type": "text"
}
}
}
]
``` 
...use simple mapping as a text field
```
"searchTerm": {
"type": "text"
},
```
Apply sorting to the results only if searching without query. When searching with query string, we expect results sorted by relevance, not in alphabetical order. 
Fixed field boosting. These must be added to the field name, otherwise it affects to the …

Search performance improvement

---

src/main/java/fi/vm/yti/terminology/api/v2/mapper/ConceptCollectionMapper.java
src/main/java/fi/vm/yti/terminology/api/v2/mapper/ConceptMapper.java
src/main/java/fi/vm/yti/terminology/api/v2/mapper/NTRFMapper.java
src/main/java/fi/vm/yti/terminology/api/v2/migration/task/V3_RDFListConversion.java
src/main/java/fi/vm/yti/terminology/api/v2/migration/v1/TermedMigrationService.java
src/main/java/fi/vm/yti/terminology/api/v2/property/Term.java
src/main/java/fi/vm/yti/terminology/api/v2/repository/TerminologyRepository.java
src/main/java/fi/vm/yti/terminology/api/v2/service/ConceptService.java
src/test/java/fi/vm/yti/terminology/api/v2/TestUtils.java
src/test/java/fi/vm/yti/terminology/api/v2/mapper/ConceptMapperTest.java
src/test/java/fi/vm/yti/terminology/api/v2/mapper/NTRFMapperTest.java
src/test/java/fi/vm/yti/terminology/api/v2/migration/RDFListConversionTest.java
src/test/java/fi/vm/yti/terminology/api/v2/service/ConceptCollectionServiceTest.java
src/test/resources/ntrf/term-and-concept-info.xml
src/test/resources/rdf-list-conversion.ttl
src/test/resources/terminology-with-concept-collections.ttl
src/test/resources/terminology-with-concepts.ttl

Store order of the data in separate property
```
test:concept-1;
skos:note                   "Test note 1"@en , "Test note 2"@en ;
term:orderedNote.    ( "Test note 2"@en  "Test note 1"@en ) .
```
Create terms as a resource with an identifier
```
test:concept-1;
skos:prefLabel          <urn:uuid:b9dd6178-57e4-45bc-841d-13cdc6057bb9> .
<urn:uuid:b9dd6178-57e4-45bc-841d-13cdc6057bb9>
rdf:type                      skos-xl:Label;
skos-xl:literalForm    "Test term"@en .
```
Other fixes
- Fix saving notes' and examples' order in NTRF import
- Save term's homograph number only if > 0
- Change status to resource (previously stored as a literal)

Handle ordered properties

---

src/main/java/fi/vm/yti/terminology/api/v2/opensearch/ConceptQueryFactory.java
src/test/resources/opensearch/concept-exceptions-request.json
src/test/resources/opensearch/concept-request.json
src/test/resources/opensearch/concept-superuser-request.json

For more relevant search result, build query string with exact match and wildcards, e.g. `test~1 *test*`.  That is: search documents matching `test` (with fuzziness 1) OR `*test*`. Exact matches will get better score, so they will be ranked higher in the results. If the query string contains space, search for exact phrase, e.g.  query string `test something` => `"test something"`.
If no status is given, use predefined status list to filter out concepts with status SUPERSEDED or RETIRED. 
See also: https://github.com/VRK-YTI/yti-common-backend/pull/8

YTI-4260 improve concept search

---

src/main/java/fi/vm/yti/terminology/api/v2/dto/CountDTO.java
src/main/java/fi/vm/yti/terminology/api/v2/endpoint/FrontendController.java
src/main/java/fi/vm/yti/terminology/api/v2/mapper/ConceptMapper.java
src/main/java/fi/vm/yti/terminology/api/v2/opensearch/ConceptQueryFactory.java
src/main/java/fi/vm/yti/terminology/api/v2/opensearch/CountQueryFactory.java
src/main/java/fi/vm/yti/terminology/api/v2/opensearch/TerminologyQueryFactory.java
src/main/java/fi/vm/yti/terminology/api/v2/service/SearchIndexService.java
src/main/java/fi/vm/yti/terminology/api/v2/service/TerminologyService.java
src/test/java/fi/vm/yti/terminology/api/v2/mapper/ConceptMapperTest.java
src/test/java/fi/vm/yti/terminology/api/v2/opensearch/CountQueryFactoryTest.java
src/test/resources/opensearch/concept-count-query.json
src/test/resources/opensearch/terminology-count-query.json

Implement count queries:
- GET /terminology-api/v2/frontend/counts
- GET /terminology-api/v2/frontend/concept-counts
- GET /terminology-api/v2/frontend/status-counts
Other fix: remove old terms from the model, when updating concept

YTI-4226 count queries

---

src/main/java/fi/vm/yti/terminology/api/v2/opensearch/ConceptQueryFactory.java
src/main/java/fi/vm/yti/terminology/api/v2/opensearch/ConceptSearchRequest.java

This is needed in datamodel application when searching concepts from all linked terminologies.

YTI-4260 support multiple namespaces in concept search

---

src/main/java/fi/vm/yti/terminology/api/v2/migration/v1/TermedMigrationController.java
src/main/java/fi/vm/yti/terminology/api/v2/migration/v1/TermedMigrationService.java
src/main/java/fi/vm/yti/terminology/api/v2/service/UriResolveService.java
src/test/java/fi/vm/yti/terminology/api/v2/service/UriResolveServiceTest.java

- update termed ids for terminologies. Previously termed node's id was added to terminology metadata, correct id is termed graph id
- fix query for getting resource type during resolving (add graph to where condition, otherwise uses default graph)
- fix resolving resources which id starts with digit (add prefix 'a' to id)
- disable migrateAll endpoint

Terminology api release fixes

---

src/main/java/fi/vm/yti/terminology/api/v2/opensearch/ConceptQueryFactory.java
src/main/java/fi/vm/yti/terminology/api/v2/opensearch/TerminologyQueryFactory.java
src/main/java/fi/vm/yti/terminology/api/v2/service/TerminologyService.java
src/test/java/fi/vm/yti/terminology/api/v2/service/TerminologyServiceTest.java
src/test/resources/opensearch/terminology-deep-request.json
src/test/resources/opensearch/terminology-deep-superuser-request.json

Add incomplete check also to additional terminologies query, because concept search might find e.g. draft concepts from incomplete terminology. Add also same query string handling implemented in [datamodel application](https://github.com/VRK-YTI/yti-datamodel-api/pull/332).
Other change: when fetching terminology, check if the prefix is in UUID format. If so, check whether it is a termed graph id.

YTI-4284 search fixes

---

src/main/java/fi/vm/yti/terminology/api/v2/endpoint/ConceptController.java
src/main/java/fi/vm/yti/terminology/api/v2/service/ConceptService.java
src/test/java/fi/vm/yti/terminology/api/v2/service/ConceptServiceTest.java

Endpoint for changing statuses: `POST /concept/{terminology prefix}/modify-statuses?oldStatus=old&newStatus=new?types=Concept,Term`
Possible to change either concepts' (type = skos:Concept) or terms' (type = skos-xl:Label) or both status.

YTI-4125 status bulk change

---

src/main/java/fi/vm/yti/terminology/api/v2/endpoint/ExportController.java
src/main/java/fi/vm/yti/terminology/api/v2/service/TerminologyService.java
src/test/java/fi/vm/yti/terminology/api/v2/service/TerminologyServiceTest.java

Export terminology as a file. Available formats: json-ld, turtle and rdf.

YTI-4289 terminology export

---

build.gradle
src/main/java/fi/vm/yti/terminology/api/v2/health/FusekiHealthChecker.java
src/main/java/fi/vm/yti/terminology/api/v2/health/OpenSearchHealthChecker.java
src/main/resources/config/application-template.properties

This will allow having readiness probes in kubernetes to stop traffic if the backend services are down.

add custom health checks for fuseki/opensearch connection
