VRK-YTI/yti-terminology-api

build.gradle, src/main/java/fi/vm/yti/terminology/api/importapi/NtrfMapper.java
YTI-1141 fixes missing () and corrects i-prepositions  from swedish description part.
=> Fixed YTI-1141, missing  svedish prepositions and () from XML-import

build.gradle
Swagger needs jaxb dependencies from javax.xml and com.sun.xml -packages
=> YTI-448 add jaxb dependencies for swagger

build.gradle, src/main/java/fi/vm/yti/terminology/api/importapi/ExportController.java, src/main/java/fi/vm/yti/terminology/api/importapi/ExportService.java, src/main/java/fi/vm/yti/terminology/api/importapi/excel/ExcelCreator.java, src/main/java/fi/vm/yti/terminology/api/importapi/excel/JSONWrapper.java, src/main/java/fi/vm/yti/terminology/api/importapi/excel/SheetDTO.java, src/test/java/fi/vm/yti/terminology/api/importapi/excel/ExcelCreatorTest.java, src/test/java/fi/vm/yti/terminology/api/importapi/excel/JSONWrapperTest.java, src/test/java/fi/vm/yti/terminology/api/importapi/excel/SheetDTOTest.java, src/test/java/fi/vm/yti/terminology/api/importapi/excel/SheetHelpers.java, src/test/resources/importapi/excel/data.json
=> Excel export

src/main/resources/logback-spring.xml
Add short version (depth = 2) of stacktrace to log message
=> YTI-1507 add stacktrace to log message

src/main/java/fi/vm/yti/terminology/api/frontend/FrontendTermedService.java
In collection list view fetch also definition and collection's members
=> YTI-1635 fetch collection definition and members

src/main/java/fi/vm/yti/terminology/api/frontend/FrontendTermedService.java, src/main/java/fi/vm/yti/terminology/api/security/AuthorizationManager.java, src/test/java/fi/vm/yti/terminology/api/security/AuthorizationManagerTest.java
* Include creator/modifier user's name to the response only if logged in user is part of the same organization
* Create unit test for `AuthorizationManager`
=> YTI-1624 User name mapping

src/main/java/fi/vm/yti/terminology/api/frontend/FrontendController.java, src/main/java/fi/vm/yti/terminology/api/frontend/FrontendElasticSearchService.java, src/main/java/fi/vm/yti/terminology/api/frontend/elasticqueries/CountQueryFactory.java, src/main/java/fi/vm/yti/terminology/api/frontend/searchdto/CountDTO.java
* Total count of concepts
* Aggregate counts of concepts by status in vocabulary
* Fetch separately count of collections in vocabulary
* In `CountDTO`, use `Map` for storing categories instead of separate dto class
=> YTI-1643 concepts' counts

src/main/java/fi/vm/yti/terminology/api/frontend/FrontendController.java, src/main/java/fi/vm/yti/terminology/api/frontend/FrontendTermedService.java, src/test/java/fi/vm/yti/terminology/api/frontend/FrontendTermedServiceTest.java
Organizations and groups are ordered alphabetically according to given language.
=> Yti 1641 org and groups alphabetical order

src/main/java/fi/vm/yti/terminology/api/frontend/elasticqueries/CountQueryFactory.java, src/test/java/fi/vm/yti/terminology/elasticsearch/query/CountQueryFactoryTest.java, src/test/resources/es/request/concept_count_request.json
- Skip concepts with status INCOMPLETE when fetching counts
- Add unit test for creating concept count request
=> YTI-1670 Filter out concepts with the status incomplete

src/main/java/fi/vm/yti/terminology/api/importapi/excel/ExcelCreator.java, src/main/java/fi/vm/yti/terminology/api/importapi/excel/JSONWrapper.java
- Fix / remove some column headers
- Instant doesn't support offsets, change to OffsetDateTime
=> YTI-1671 fix date handling and column names

build.gradle
Upgrade spring boot to 2.5.12
Note: This is a hotfix to master branch, because develop branch is not production ready. Cherry-pick the commit to develop branch later
=> YTI-1790 spring boot upgrade

src/main/java/fi/vm/yti/terminology/api/migration/AttributeIndex.java, src/main/java/fi/vm/yti/terminology/api/migration/task/V22_LinkTermEquivalencyAndSubjectAreaProperties.java
- Added new concept properties subjectArea and externalLink
- Added new term property termEquivalencyRelation
=> YTI-1724 Add new properties

src/main/java/fi/vm/yti/terminology/api/frontend/FrontendController.java, src/main/java/fi/vm/yti/terminology/api/validation/VocabularyNodeValidator.java, src/test/java/fi/vm/yti/terminology/api/frontend/FrontendControllerTest.java
* Create separate endpoint with validation for creating new terminology
* Enable validations
=> YTI-1886 new endpoint for validated terminology

src/main/java/fi/vm/yti/terminology/api/util/IndexUtil.java, src/test/java/fi/vm/yti/terminology/elasticsearch/IndexUtilTest.java
- Fix getting default value
- Check if result is not empty
- Add unit test
=> YTI-1871 Fix sort label creation

src/main/java/fi/vm/yti/terminology/api/importapi/excel/ExcelCreator.java
At least period (.) causes problems in the filename
=> YTI-1448 sanitize excel filename

build.gradle
=> YTI-1944 library update

src/main/java/fi/vm/yti/terminology/api/frontend/elasticqueries/CountQueryFactory.java, src/main/java/fi/vm/yti/terminology/api/frontend/elasticqueries/TerminologyQueryFactory.java, src/main/java/fi/vm/yti/terminology/api/frontend/searchdto/CountDTO.java, src/main/java/fi/vm/yti/terminology/api/frontend/searchdto/TerminologySearchRequest.java, src/test/java/fi/vm/yti/terminology/elasticsearch/query/CountQueryFactoryTest.java, src/test/resources/es/response/vocabulary_only_count_response.json
Add language to search payload
```
{
"query": "",
"statuses": [],
"groups": [],
"organizations": [],
"searchConcepts": true,
"prefLang": "fi",
"pageSize": 10,
"pageFrom": 0,
"language": "sv"
}
``` 
Add vocabulary language to counts aggregation
```
{
"totalHitCount": 13,
"counts": {
"categories": {
"Concept": 0,
"TerminologicalVocabulary": 13,
"OtherVocabulary": 0,
"Collection": 0
},
"statuses": {
"DRAFT": 10,
"VALID": 2
},
"groups": {
"fa57fa33-4f13-384f-9273-5e4e9b3b7837": 10
},
"languages": {
"fi": 13,
"sv": 9,
"en": 7
}
}
}
```
=> YTI-1920 Language search options

src/main/java/fi/vm/yti/terminology/api/importapi/ExportService.java, src/main/java/fi/vm/yti/terminology/api/importapi/excel/ExcelCreator.java, src/test/java/fi/vm/yti/terminology/api/importapi/excel/ExcelCreatorTest.java
If user belongs to organization with role admin or terminology editor, add editorial note property to excel export
=> YTI-1718 Add editorial note to excel export

src/main/resources/config/application-template.properties
Changelog: 
- Updated application-template.properties file.
- Ports are not updated as those depend on how the developer is running their other modules
=> Yti 1982 dev env improvement

src/main/java/fi/vm/yti/terminology/api/frontend/elasticqueries/ConceptQueryFactory.java, src/main/java/fi/vm/yti/terminology/api/frontend/elasticqueries/TerminologyQueryFactory.java, src/main/java/fi/vm/yti/terminology/api/frontend/searchdto/TerminologyDTO.java, src/main/java/fi/vm/yti/terminology/api/frontend/searchdto/TerminologySimpleDTO.java, src/test/java/fi/vm/yti/terminology/elasticsearch/query/TerminologyQueryFactoryTest.java, src/test/resources/es/response/vocabulary_response.json
Changes in this PR:
- Terminology type added to terminologies when using `/searchTerminology` endpoint
=> Terminology type added to search results

src/main/java/fi/vm/yti/terminology/api/frontend/FrontendController.java, src/main/java/fi/vm/yti/terminology/api/validation/BaseValidator.java, src/main/java/fi/vm/yti/terminology/api/validation/GenericDeleteAndSaveValidator.java, src/main/java/fi/vm/yti/terminology/api/validation/ValidationConstants.java, src/main/java/fi/vm/yti/terminology/api/validation/VocabularyNodeValidator.java, src/test/java/fi/vm/yti/terminology/api/frontend/FrontEndControllerInternalNodeTests.java, src/test/java/fi/vm/yti/terminology/api/frontend/FrontendControllerTest.java
Added validation for text length on most properties and prefix
Rearranged Vocabulary node validator
Created ValidationConstants
MOCK API call tests for checking length
=> Yti 2013 text properties length

src/main/java/fi/vm/yti/terminology/api/importapi/ImportController.java, src/main/java/fi/vm/yti/terminology/api/importapi/excel/ExcelParser.java
- add mapping to path /api/v1/frontend/import
- fix collection's description property name ("definition" in the database)
=> Excel import fixes

src/main/java/fi/vm/yti/terminology/api/frontend/elasticqueries/TerminologyQueryFactory.java, src/main/resources/create_index_default.json
- Use alphabetical order only if no query provided
- Increased ngram minimum size to improve search results qulity
=> YTI-2056, YTI-1984 search improvements

src/main/java/fi/vm/yti/terminology/api/validation/GenericDeleteAndSaveValidator.java
Concept might have multiple prefLabelXl reference attributes if multiple languages
=> YTI-2074 fix checking prefLabelXl

src/main/java/fi/vm/yti/terminology/api/frontend/FrontendController.java, src/main/java/fi/vm/yti/terminology/api/frontend/FrontendElasticSearchService.java, src/main/java/fi/vm/yti/terminology/api/validation/GenericDeleteAndSaveValidator.java, src/main/java/fi/vm/yti/terminology/api/validation/ValidationConstants.java, src/test/java/fi/vm/yti/terminology/api/frontend/FrontEndControllerInternalNodeTests.java, src/test/java/fi/vm/yti/terminology/api/frontend/FrontendControllerTest.java
Changelog:
- Way more comprehensive validation for generic node
- Tests for mismatched data
- tests for prefix
- changed getStatusNames into a constant since we only need to get them once
Looks like the waiting time inceases slighlty for these requests when checking network tab on browser.
=> Yti 2055 better validation backend

src/main/java/fi/vm/yti/terminology/api/frontend/FrontendController.java, src/main/java/fi/vm/yti/terminology/api/frontend/FrontendTermedService.java, src/test/java/fi/vm/yti/terminology/api/frontend/FrontEndControllerInternalNodeTests.java
Merging nodes ([PR](https://github.com/VRK-YTI/yti-terminology-api/pull/75)) after updating caused some unexpected behaviour -> roll back
=> YTI-2095 revert merging nodes on update

src/main/java/fi/vm/yti/terminology/api/resolve/ResolveController.java, src/main/resources/config/application-template.properties, src/test/java/fi/vm/yti/terminology/api/resolve/ResolveControllerTest.java
Use _v2 suffix to redirect user to beta url defined in application properties
=> YTI-2132 support _v2 suffix in env parameter

src/main/java/fi/vm/yti/terminology/api/index/IndexTermedService.java
Optimize termed queries performed after concept indexing
=> YTI-2115 optimize concept indexing

src/main/java/fi/vm/yti/terminology/api/frontend/FrontendTermedService.java, src/main/java/fi/vm/yti/terminology/api/index/IndexTermedService.java
- Change that indexing won't crash if vocabulary node not found
- If creating new version fails, delete created graph and related types
=> YTI-2115 fetch vocabulary fix

src/main/java/fi/vm/yti/terminology/api/index/IndexTermedService.java, src/main/java/fi/vm/yti/terminology/api/util/JsonUtils.java
Add missing findSingle method call
=> YTI-2115 fix fetching terminology node

src/main/java/fi/vm/yti/terminology/api/validation/GenericDeleteAndSaveValidator.java, src/test/java/fi/vm/yti/terminology/api/frontend/FrontEndControllerInternalNodeTests.java
Changelog: 
add termEquivalency check
save getProperties to variable
change size to isempty
remove extra termConjugation check
=> YTI-2055 term equivalency check

src/main/java/fi/vm/yti/terminology/api/validation/GenericDeleteAndSaveValidator.java
Changelog:
- Added verb to wordClass in term
- Fixes 400 BAD REQUEST
=> YTI-2206: add wordClass check to backend

src/main/java/fi/vm/yti/terminology/api/frontend/FrontendTermedService.java
- Catch all exceptions and clean up possibly created resources in case of error
- Use synchronised api calls when creating graph and types. This should fix or at least mitigate write lock errors
=> YTI-2176 catch exceptions and add sync parameter

src/main/java/fi/vm/yti/terminology/api/importapi/simpleexcel/SimpleExcelParser.java
Changelog:
- trim whitespace and non-break spaces from text
- Check if row does not have any data
These changes will make simple excel import less prone to human error
=> YTI-2275: check for empty text and remove any whitespace characters.

src/main/java/fi/vm/yti/terminology/api/importapi/simpleexcel/SimpleExcelParser.java, src/main/java/fi/vm/yti/terminology/api/validation/GenericDeleteAndSaveValidator.java, src/main/java/fi/vm/yti/terminology/api/validation/ValidationConstants.java, src/main/java/fi/vm/yti/terminology/api/validation/VocabularyNodeValidator.java, src/test/java/fi/vm/yti/terminology/api/frontend/FrontEndControllerInternalNodeTests.java, src/test/java/fi/vm/yti/terminology/api/frontend/FrontendControllerTest.java
Longer text fields (5000) for
- Vocabulary description
- Concept definition
- Collection definition
Cleaned code based on sonarqube issues
Linked
https://github.com/VRK-YTI/yti-terminology-ui/pull/320
=> YTI-2301 - Longer definition for all definition/description fields

src/main/java/fi/vm/yti/terminology/api/resolve/ResolveController.java
Changelog:
- Sanitize html on URI error
- Fixed sonarqube issues on ResolveController file
=> escape uri if when returning an error

src/main/java/fi/vm/yti/terminology/api/importapi/ImportService.java, src/main/java/fi/vm/yti/terminology/api/importapi/excel/ExcelParser.java, src/main/java/fi/vm/yti/terminology/api/importapi/simpleexcel/SimpleExcelParser.java, src/test/java/fi/vm/yti/terminology/api/importapi/ImportServiceTest.java
Changelog:
- Check if correct excel import is being used
-  Simple check for amount of sheets (tabs) in excel file
- message in api response will be `incorrect-sheet-count`
- Unit tests
- Fix a bunch of sonarqube issues
=> YTI-2232: Check if correct excel import is being used.

src/main/java/fi/vm/yti/terminology/api/frontend/FrontendTermedService.java, src/main/java/fi/vm/yti/terminology/api/importapi/ImportService.java
Changelog:
- ensureTermedUser to public function
- Logger info for creating termed user
- Excel import and simple excel import added ensure termed user
- Fixed more sonarqube issues
=> YTI-2342: Ensure termed user on excel imports

src/main/java/fi/vm/yti/terminology/api/importapi/simpleexcel/SimpleExcelParser.java, src/main/java/fi/vm/yti/terminology/api/validation/GenericDeleteAndSaveValidator.java, src/main/java/fi/vm/yti/terminology/api/validation/ValidationConstants.java, src/main/java/fi/vm/yti/terminology/api/validation/VocabularyNodeValidator.java, src/test/java/fi/vm/yti/terminology/api/frontend/FrontEndControllerInternalNodeTests.java, src/test/java/fi/vm/yti/terminology/api/frontend/FrontendControllerTest.java
- Increase length of ValidationConstants.TEXT_AREA_MAX_LENGTH
- Change DEFINITION_MAX_LENGTH to use TEXT_AREA_MAX_LENGTH instead
=> YTI-2353: Increase textarea limit

build.gradle, src/main/java/fi/vm/yti/terminology/api/frontend/FrontendTermedService.java
Changelog:
- Add jacoco test reports and enable them in CI (develop build)
- fix search term to get search term rather than notRecommendedSynonym
=> YTI-2366: fix mass status count queries

src/main/java/fi/vm/yti/terminology/api/validation/GenericDeleteAndSaveValidator.java, src/test/java/fi/vm/yti/terminology/api/frontend/FrontEndControllerInternalNodeTests.java
Changes in this PR:
- Collection prefLabel and definition checking disabled
- Only prefLabel count is checked to be above 0 to be valid
=> Collection definition check removed

src/main/java/fi/vm/yti/terminology/api/frontend/elasticqueries/TerminologyQueryFactory.java, src/main/java/fi/vm/yti/terminology/api/frontend/searchdto/TerminologySearchRequest.java
Changelog:
- added possibility to filter groups with groupNotation
- allow hiding label highlighting with optional parameter 
- Fixed some sonarqube issues
=> YTI-2483: added possibility to filter groups with groupNotation

src/main/java/fi/vm/yti/terminology/api/importapi/ExportService.java, src/main/java/fi/vm/yti/terminology/api/importapi/excel/ExcelCreator.java, src/main/java/fi/vm/yti/terminology/api/importapi/excel/ExcelParser.java, src/main/java/fi/vm/yti/terminology/api/importapi/excel/JSONWrapper.java
- Remove unused mapping for concept links, because they are generated nowadays in separate sheet
- Fix a couple sonar errors
=> YTI-2485 fix concept link export

src/main/java/fi/vm/yti/terminology/api/frontend/FrontendTermedService.java
Changelog:
-Remove editorial note from dto if user is not part of org
=> YTI-2535: Remove editorial note from dto if user is not part of org

src/main/java/fi/vm/yti/terminology/api/importapi/simpleexcel/SimpleExcelParser.java
Save multiline properties in reverse order so the first item in the excel cell will be added last -> in the site it will be on top of the list
=> YTI-2612 Change multiline properties saving order

src/main/java/fi/vm/yti/terminology/api/importapi/excel/ExcelParser.java, src/main/java/fi/vm/yti/terminology/api/importapi/excel/JSONWrapper.java, src/main/java/fi/vm/yti/terminology/api/integration/IntegrationService.java, src/test/java/fi/vm/yti/terminology/api/importapi/ImportServiceTest.java, src/test/java/fi/vm/yti/terminology/api/importapi/excel/ExcelParserTest.java
Fix uri handling in integration endpoint and excel export/import
=> YTI-2584 fix uri handling after removing suffix

src/main/java/fi/vm/yti/terminology/api/importapi/NtrfMapper.java, src/test/java/fi/vm/yti/terminology/api/importapi/NtrfTest.java, src/test/resources/concept-definition-and-note.xml
Fix handling external concept links. If they are defined in DEF, EXAMP or NOTE elements, add concept link element to the concept if not already exist.
=> YTI-3329 External concept links

Dockerfile, src/main/java/fi/vm/yti/terminology/api/importapi/NtrfMapper.java, src/test/resources/concept-definition-and-note.xml
merge develop to master for a new release
=> develop to master 2024-05-21

build.gradle, src/main/java/fi/vm/yti/terminology/api/v2/StartUpListener.java
Upgrade yti-spring-migration ([PR](https://github.com/VRK-YTI/yti-spring-migration/pull/3)) and git-properties gradle plugin
=> YTI-3919 Library updates

src/main/java/fi/vm/yti/terminology/api/v2/endpoint/RequestsController.java
Add controller for handling user requests. Service implementation in common-backend: https://github.com/VRK-YTI/yti-common-backend/pull/10
=> YTI-4103 add user request handling

build.gradle, src/test/resources/integration/resource-search-request.json, src/test/resources/opensearch/terminology-deep-request.json, src/test/resources/opensearch/terminology-deep-superuser-request.json, src/test/resources/opensearch/terminology-request.json
fix tests after common-backend-lib update
=> common backend update

src/main/java/fi/vm/yti/terminology/api/v2/service/IndexService.java
Remove concepts from index after terminology has been removed
=> YTI-4348 Fix indexing after terminology deletion
